trigger:
  include:
    branch:
      - main

pr: none

variables: 
  - group: SEMAPHORE-UI

pool:
  - name: wblocal

stages:

- stage: getChanges

- stage: projects

- stage: keys

- stage: iventory

- stage: repository